const events = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SELECT_MODULE: 'SELECT_MODULE',
  CHANGE_ACTIVE_AFFILIATION: 'CHANGE_ACTIVE_AFFILIATION',
  CHANGE_SERVICE_POINT: 'CHANGE_SERVICE_POINT',
  ERROR: 'ERROR',
};

export default events;
