name: Centralized workflow
on: 
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ui:
    uses: folio-org/.github/.github/workflows/ui.yml@v1
    if: github.ref_name == github.event.repository.default_branch || github.event_name != 'push' || github.ref_type == 'tag'
    secrets: inherit
    with:
      jest-enabled: true
      jest-test-command: yarn run test:jest
      bigtest-enabled: true
      bigtest-test-command: xvfb-run --server-args="-screen 0 1024x768x24" yarn run test:bigtest $YARN_TEST_OPTIONS --karma.singleRun --karma.browsers ChromeDocker --karma.reporters mocha junit --coverage

